name: Danger

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: danger/python@f0ce9ea
    - name: Run Danger
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
